print('======Desafio 009======')
# Faça um programa que leia um número inteiro e mostre na tela a sua tabuada
valor = int(input('Digite um número inteiro: '))
v1 = (valor*1)
v2 = (valor*2)
v3 = (valor*3)
v4 = (valor*4)
v5 = (valor*5)
v6 = (valor*6)
v7 = (valor*7)
v8 = (valor*8)
v9 = (valor*9)
v10 = (valor*10)
print('------TABUADA DE {}------'.format(valor))
print('{} x 1 = {}'.format(valor,v1))
print('{} x 2 = {}'.format(valor,v2))
print('{} x 3 = {}'.format(valor,v3))
print('{} x 4 = {}'.format(valor,v4))
print('{} x 5 = {}'.format(valor,v5))
print('{} x 6 = {}'.format(valor,v6))
print('{} x 7 = {}'.format(valor,v7))
print('{} x 8 = {}'.format(valor,v8))
print('{} x 9 = {}'.format(valor,v9))
print('{} x 10 = {}'.format(valor,v10))
